#:schema https://dystroy.org/bacon/.bacon.schema.json

[jobs.check]
command = ['cargo', 'check', '--all-targets']

[jobs.clippy]
command = ['cargo', 'clippy', '--all-targets', '--', '-D', 'warnings']

[jobs.test]
command = ['cargo', 'test']
